name: cppcheck-action-test

on:
  pull_request:
    branches: [main]

jobs:
  build:
    name: cppcheck-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
          
      - name: cppcheck
        uses: deep5050/cppcheck-action@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN}}
          std: c89
          other_options: --suppress=missingInclude --suppress=unmatchedSuppression --suppress=missingIncludeSystem --suppress=unusedFunction